<div class="p-6 max-h-[90vh] overflow-y-auto">
    <button class="absolute top-2 right-2 text-gray-600 hover:text-gray-800 dark:text-gray-400 dark:hover:text-gray-200 focus:outline-none text-3xl" wire:click="closeModal">
        &times;
    </button>
    
    @if($report)
        <div class="mb-6">
            <div class="flex items-center justify-between mb-4">
                <h2 class="text-2xl font-bold text-gray-900 dark:text-gray-100">{{ $report->title }}</h2>
                <button wire:click="$dispatch('openModal', { component: 'modals.disaster-report-modal', arguments: { report: {{ $report->id }} } })" class="text-indigo-600 hover:text-indigo-900 dark:text-indigo-400 dark:hover:text-indigo-300">
                    <i class="fas fa-edit"></i> Edit
                </button>
            </div>
            
            <div class="flex flex-wrap gap-4 text-sm text-gray-600 dark:text-gray-400 mb-4">
                <div>
                    <span class="font-medium">Type:</span>
                    @if($report->report_type === 'situation')
                        <span class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-blue-100 text-blue-800 dark:bg-blue-900 dark:text-blue-200 ml-2">
                            Situation Report
                        </span>
                    @elseif($report->report_type === 'damage_assessment')
                        <span class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-red-100 text-red-800 dark:bg-red-900 dark:text-red-200 ml-2">
                            Damage Assessment
                        </span>
                    @elseif($report->report_type === 'recovery_progress')
                        <span class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-200 ml-2">
                            Recovery Progress
                        </span>
                    @else
                        <span class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-gray-100 text-gray-800 dark:bg-gray-700 dark:text-gray-200 ml-2">
                            Final Report
                        </span>
                    @endif
                </div>
                <div>
                    <span class="font-medium">Event:</span> {{ $report->disasterEvent->title }}
                </div>
                <div>
                    <span class="font-medium">Date:</span> {{ $report->report_date->format('F d, Y') }}
                </div>
                <div>
                    <span class="font-medium">Generated By:</span> {{ $report->generatedBy->name }}
                </div>
            </div>
        </div>

        <div class="bg-white dark:bg-gray-800 rounded-lg shadow p-6">
            <h3 class="text-lg font-semibold text-gray-900 dark:text-gray-100 mb-4">Report Content</h3>
            <div class="prose dark:prose-invert max-w-none text-gray-700 dark:text-gray-300 whitespace-pre-wrap">
                {!! $report->content !!}
            </div>
        </div>

        @if($report->attachments && count($report->attachments) > 0)
            <div class="mt-6 bg-white dark:bg-gray-800 rounded-lg shadow p-6">
                <h3 class="text-lg font-semibold text-gray-900 dark:text-gray-100 mb-4">Attachments</h3>
                <ul class="space-y-2">
                    @foreach($report->attachments as $attachment)
                        <li class="flex items-center gap-2 text-sm text-gray-600 dark:text-gray-400">
                            <i class="fas fa-paperclip"></i>
                            <span>{{ basename($attachment) }}</span>
                        </li>
                    @endforeach
                </ul>
            </div>
        @endif
    @endif
</div>
